# For development environments only
version: '3.7'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app/
    # ports: # for localhost setup
    #   - 8080:80 
    environment:
      # - HOST= <e.g. localhost, api.something.com>
      - CHANNELS_REDIS_HOST=redis

  # redis channel layer
  redis:
    image: redis:5
      
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.release
      args:
        # - BACKEND_HOST= <e.g. localhost, api.something.com>
    volumes:
      - ./frontend:/app
      - '/app/node_modules'
    # ports: # for localhot setup
    #   - 80:80